[project]
name = "uv"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.116.1",
    "logfire>=4.2.0",
    "mcp>=1.12.4",
    "mcp-server-fetch>=2025.1.17",
    "pydantic-ai>=0.6.2",
    "uvicorn>=0.35.0",
]

